spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.5:3306/gfb0810?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&&useSSL=true
    username: gfb0810
    password: GOFOBAO@0701.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 192.168.1.5
    password: gofobao@123
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: gofobao
    password: gofobao
  mail:
    host: smtp.qq.com
    port: 587
    username: service@gofobao.com
    password: gofobaochina123
    default-encoding: UTF-8
  thymeleaf:
    mode: LEGACYHTML5
  profiles:
    active: def
server:
  port: 8080
jwt: #JWT 安全配置
  header: Authorization
  secret: WWW.gOf0b@o.c0m@0701
  expiration: 2592000
  prefix: Bearer
  #七牛
qiniu:
    domain: test.img.gofobao.com
    bucket: test
    ak : yevGNMoheNL4EGIencz8E-ohrPzMqLwchW9SvX9e
    sk : GjGZAJBUpe8UzPoWmKeKBPSi7Kq_IshmuW-UC89o


#风车理财
windmill:
  des-key: 2l0IYbNnRcShWOM9Q5Ej0A3gCEP07LBS #des加密key值
  request-address: http://121.42.52.42  #风车理财请求地址
  short-name: gfb #风车理财分配给平台的简称
  from: wrb #风车理财简称
  local-des-key : 2l0IYbNnRcShWOM9Q5Ej0A3gCGOFOBAO #和风车理财交互时 平台的关键字段加密key值
  notify-address:  http://121.42.52.42/wrb/ws_info_call_back.json  #通知风车理财接口

jixin: #银行存管
  keysPath: D:/sign/guangfubao_uat.p12 #私钥路径
  keysPassword: guangfubao_uat@2016 #私钥密码
  crtPath: D:/sign/fdep.crt #服务端证书文件路径
  url: http://uat.gofobao.com #即信服务器路径
  htmlUrl: https://access.credit2go.cn #即信服务器路径
  version: 10 #版本号
  instCode: "00960001" #机构代码
  bankCode: "30050000" #交易机构代码
  query-time-init: "20161011" # 与存管系统查询时间
gofobao:
  dev: true # 开发环境
  javaDomain:  http://lang.hk1.mofasuidao.cn
  webDomain:  http://lang.hk1.mofasuidao.cn
  h5Domain:  http://ng.hk1.mofasuidao.cn
  imageDomain : http://www.gofobao.com
  file-url: http://uat.gofobao.com/escrow/file/download #文件请求下载链接

  save-file-path: D:/statistice/   #文件本地保存的路径
  captcha: false # 全站是否开启图形验证码验证
  close-email-send: true # 关闭邮箱发送
  close-phone-send: true # 关闭短信发送
  close-jixin-log: false # 关闭即信log
  aliyun-bankinfo-url: http://jisuyhkgsd.market.alicloudapi.com/bankcard/query
  aliyun-bankaps-url: http://cnaps.market.alicloudapi.com/lianzhuo/querybankaps
  aliyun-bankinfo-appcode: 1fa8442456704a4686d950b099c188b9 #阿里云api管理中的appcode
  flowConfig: #易蜂享
    url: http://xc.aipipi.mobi/trafgatewate/apply.do
    id: 10
    key: 1b5e8124fe
  jiguang:
    AppKey: ce7616b0fc76f923a1b53b30
    MasterSecre : d4b742ae7cc3e4be1d6a95c3
logging:
  file: /Users/Max/logs/logback.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
#    org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
#    com.gofobao: DEBUG
    root: INFO

