spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.27.31.182:3306/gofobao9?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&&useSSL=true
    username: gofobao9
    password: GOFOBAO@0701.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect


aliyun:
  keys: # 阿里云
    accessKey: pcJnstgkn9RGgE3f
    secretKey: iZayTXG25VF2uYNN6BxczNI4kc0y4s
    onsAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
server:
  port: 8080