spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.3:3306/gofobao0627?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&&useSSL=true
    username: gofobao0627
    password: GOFOBAO@0701.
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 192.168.1.3
    password: gofobao@123
    port: 6379
  rabbitmq:
    host: 192.168.1.3
    port: 5672
    username: gofobao
    password: gofobao
  mail:
    host: smtp.qq.com
    port: 587
    username: service@gofobao.com
    password: gofobaochina123
    default-encoding: UTF-8
server:
  port: 9090
jwt: #JWT 安全配置
  header: Authorization
  secret: WWW.gOf0b@o.c0m@0701
  expiration: 2592000
  prefix: Bearer

jixin: #银行存管
  keysPath: /root/jenkins/certs/guangfubao_sit.p12 #私钥路径
  keysPassword: guangfubao_sit@2016 #私钥密码
  crtPath: /root/jenkins/certs/fdep.crt #服务端证书文件路径
  url: https://test.credit2go.cn #即信服务器路径
  version: 10 #版本号
  instCode: "00960001" #机构代码
  bankCode: "30050000" #交易机构代码
  redPacketAccountId: "6212461270000000444" #红包账户
  handlingChargeAccountId: "6212461270000000360" #电子手续费账户
gofobao:
  javaDomain: http://max.hk1.mofasuidao.cn
  webDomain: http://max.hk1.mofasuidao.cn
  h5Domain: http://ng.hk1.mofasuidao.cn
#  javaDomain: http://ogmax.ngrok.club
#  webDomain: http://ogmax.ngrok.club
#  h5Domain: http://ogmax.ngrok.club
  imageDomain : http://www.gofobao.com
  captcha: false # 全站是否开启图形验证码验证
  close-email-send: true # 关闭邮箱发送
  close-phone-send: true # 关闭短信发送
  aliyun-bankinfo-url: http://jisuyhkgsd.market.alicloudapi.com/bankcard/query
  aliyun-bankaps-url: http://cnaps.market.alicloudapi.com/lianzhuo/querybankaps
  aliyun-bankinfo-appcode: 1fa8442456704a4686d950b099c188b9 #阿里云api管理中的appcode
logging:
  file: /var/log/apllo.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
#    org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
#    com.gofobao: DEBUG
    root: INFO
