spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rdszi3qjazi3qja.mysql.rds.aliyuncs.com:3306/gfb02?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&&useSSL=true
    username: gfb02
    password: gfb02secret
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    password: Va48LPm13dcD7dBm
    port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: gofobao
    password: WWW.gofobao.com@0701...
  mail:
    host: smtp.qq.com
    port: 587
    username: service@gofobao.com
    password: gofobaochina123
    default-encoding: UTF-8
  hymeleaf:  #模版引擎配置
      mode: HTML5
      encoding: UTF-8
      content-type: text/html
      cache: false
      enabled: true
jwt: #JWT 安全配置
  header: Authorization
  secret: WWW.gOf0b@o.c0m@07010101
  expiration: 2592000
  prefix: Bearer
qiniu: #七牛
    domain: img.gofobao.com
    bucket: gofobao
    ak : yevGNMoheNL4EGIencz8E-ohrPzMqLwchW9SvX9e
    sk : GjGZAJBUpe8UzPoWmKeKBPSi7Kq_IshmuW-UC89o
server:
  port: 8765

windmill: #风车理财
  des-key: 2l0IYbNnRcShWOM9Q5Ej0A3gCEP07LBS #des加密key值
  request-address: http://121.42.52.42  #风车理财请求地址
  short-name: gfb #风车理财分配给平台的简称
  from: wrb #风车理财简称
  local-des-key : 2l0IYbNnRcShWOM9Q5Ej0A3gCGOFOBAO #和风车理财交互时 平台的关键字段加密key值
  notify-address:  http://121.42.52.42/wrb/ws_info_call_back.json  #通知风车理财接口
jixin: #银行存管
  keysPassword: guangfubao@2016 #私钥密码
  url: https://finance.credit2go.cn/escrowll #即信服务器路径
  htmlUrl: https://finance.credit2go.cn/escrowll #即信服务器路径
  file-url: https://finance.credit2go.cn/escrowll/file/download #文件请求下载链接
  save-file-path: /www/apiPortal/admin/statistice/   #文件本地保存的路径
  version: 10 #版本号
  product-no: "0110" # 产品编号
  bank-no: "3005" #银行代码
  instCode: "00960001" #机构代码
  bankCode: "30050000" #交易机构代码
  query-time-init:  # 与存管系统查询时间
  crt-path: /www/apiPortal/admin/cert/jixin/cs_jx.crt # crt证书路径
  p12-path: /www/apiPortal/admin/cert/jixin/guangfubao.p12 # p12证书路径
gofobao:
  dev: false # 开发环境
  javaDomain:  http://api.gofobao.com
  h5Domain:  http://m.gofobao.com
  imageDomain : http://www.gofobao.com/
  pcDomain: http://www.gofobao.com
  captcha: false # 全站是否开启图形验证码验证
  close-email-send: false # 关闭邮箱发送
  close-phone-send: false # 关闭短信发送
  close-jixin-log: false # 关闭即信log
  aliyun-bankinfo-url: http://jisuyhkgsd.market.alicloudapi.com/bankcard/query
  aliyun-bankaps-url: http://cnaps.market.alicloudapi.com/lianzhuo/querybankaps
  aliyun-bankinfo-appcode: 1fa8442456704a4686d950b099c188b9 #阿里云api管理中的appcode
  flowConfig: #易蜂享
      url: http://xc.aipipi.mobi/trafgatewate/apply.do
      id: 10
      key: 1b5e8124fe
    jiguang:
      AppKey: ce7616b0fc76f923a1b53b30
      MasterSecre : d4b742ae7cc3e4be1d6a95c3
  logging:
    file: /www/apiPortal/admin/logs/apollo.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework.web: INFO
      org.hibernate: INFO
      com.gofobao: INFO
      root: INFO

